name: Restrict PR to Master
on:
  pull_request:
    branches: [master]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR comes from dev
        env:
          PR_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          if [[ "$PR_BRANCH" != "dev" ]]; then
            echo "❌ Only PRs from dev → master are allowed."
            exit 1
          fi
